<?php

namespace Tests\CodeKatas;
use PHPUnit\Framework\TestCase;

class BubbleSortTest extends TestCase
{

    protected $dataArray;

    protected $bubbleSort;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->dataArray = [
            10, 5, 58, 86, 1
        ];

        $this->bubbleSort = new BubbleSort;
    }

    public function testTheFirstElementIs1()
    {
        $dataArraySorted = $this->bubbleSort->sort();
        $this->assertEquals($dataArraySorted[0], 1);
    }

    public function testTheSecondElementIs1()
    {
        $dataArraySorted = $this->bubbleSort->sort();
        $this->assertEquals($dataArraySorted[1], 5);
    }

    public function testTheThirdElementIs1()
    {
        $dataArraySorted = $this->bubbleSort->sort();
        $this->assertEquals($dataArraySorted[2], 10);
    }

    public function testTheQuarterElementIs1()
    {
        $dataArraySorted = $this->bubbleSort->sort();
        $this->assertEquals($dataArraySorted[3], 58);
    }

    public function testTheFifthElementIs1()
    {
        $dataArraySorted = $this->bubbleSort->sort();
        $this->assertEquals($dataArraySorted[4], 86);
    }

}
